### ISSUE TITLE
After routeros is updated to 7.11.2, maltrail is not displayed at all

### ISSUE THREAD

**Issue by Young-3** [Lukas0025/maltrail-mikrotik-docker#2]
```
-R] > /tool/sniffer/print  
                     only-headers: no
                     memory-limit: 100KiB
                    memory-scroll: yes
                        file-name: 
                       file-limit: 1000KiB
                streaming-enabled: yes
                 streaming-server: 10.123.0.252:37008
                    filter-stream: yes
                 filter-interface: ether3,pppoe-out1,bonding-wan,ether1-wan,ether2-wan
               filter-mac-address: 
           filter-src-mac-address: 
           filter-dst-mac-address: 
              filter-mac-protocol: 
                filter-ip-address: 
            filter-src-ip-address: 
            filter-dst-ip-address: 
              filter-ipv6-address: 
          filter-src-ipv6-address: 
          filter-dst-ipv6-address: 
               filter-ip-protocol: tcp,udp,icmp,ipsec-esp
                      filter-port: 
                  filter-src-port: 
                  filter-dst-port: 
                      filter-vlan: 
                       filter-cpu: 
                      filter-size: 
                 filter-direction: any
  filter-operator-between-entries: or
                          running: yes
```

```
root@ids2mikrotik:/home/zmax# docker ps
CONTAINER ID   IMAGE      COMMAND                   CREATED       STATUS        PORTS                                                                                                                    NAMES
aab8850b1f40   maltrail   "/bin/sh -c 'bash -c…"   6 weeks ago   Up 35 hours   8337/udp, 0.0.0.0:8337-8338->8337-8338/tcp, :::8337-8338->8337-8338/tcp, 0.0.0.0:37008->37008/udp, :::37008->37008/udp   pensive_goldstine
```
